version: '2'

volumes:
  postgresql-volume:
    external: true

services:
  db:
    build: postgres-dockerfile
    restart: unless-stopped
    env_file:
      - ./postgres-dockerfile/postgres.env
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    expose:
      - "5432"

  musicbrainz:
    build: musicbrainz-dockerfile
    ports:
      - "5000:5000"
    volumes:
      - d:\MetaBrainz\dbdump:/media/dbdump
    restart: "no"
    env_file:
      - ./postgres-dockerfile/postgres.env
    environment:
      - MUSICBRAINZ_USE_PROXY=1
    depends_on:
      - db
      - search
      - redis

  indexer:
    build: indexer-dockerfile
    depends_on:
      - db
    volumes:
      - d:\MetaBrainz\indexdata:/home/search/indexdata

  search:
    build: search-dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - d:\MetaBrainz\indexdata:/home/search/indexdata

  redis:
    image: redis:3.2.1
    restart: unless-stopped
    expose:
      - "6379"
